name: wrappedincolour
favicon: null
layout_spectrum: 0.99682
typography_spectrum: 0.50742
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#db1811'
    - '#006dc5'
    - '#666855'
    - '#cbdf99'
    - '#481f3b'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
