name: wrappedincolour
favicon: null
layout_spectrum: 0.5345930550247431
typography_spectrum: 0.79562510503456
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.2438056762330234
  lightness: 0.021805538330227137
  saturation: 0.20780437206849456
  rhythmicContrast: 0.5352397363167256
purpose: []
