typography_spectrum: 0.50742
color:
  brandColors:
    - '#db1811'
    - '#006dc5'
    - '#666855'
    - '#cbdf99'
    - '#481f3b'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.24894
analytics:
  google: null
  facebook: null
  twitter: null
name: wrappedincolour
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: ''
description: Where you can find hand-knitted items
purpose: []
